"""Derive website assets directly from the approved PNG masters. Requires Pillow."""
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont
import hashlib
import json

ROOT = Path(__file__).resolve().parent.parent
config = json.loads((ROOT / 'config/personas-v2.json').read_text())
records = []

for persona in config['personas']:
    base = ROOT / persona['assetRoot']
    master = base / 'master/character.png'
    assert hashlib.sha256(master.read_bytes()).hexdigest() == persona['source']['sha256']
    with Image.open(master) as image:
        assert image.mode == 'RGBA' and image.size == (1086, 1448)
        for width in (360, 720, 1086):
            height = width * 4 // 3
            resized = image.resize((width, height), Image.Resampling.LANCZOS)
            for extension, options in [('webp', {'quality': 88, 'method': 6}), ('avif', {'quality': 85, 'speed': 6})]:
                output = base / 'web' / f'character-{width}.{extension}'
                output.parent.mkdir(parents=True, exist_ok=True)
                resized.save(output, **options)
                records.append({'file': str(output.relative_to(ROOT)), 'width': width, 'height': height, 'bytes': output.stat().st_size, 'sha256': hashlib.sha256(output.read_bytes()).hexdigest(), 'sourceSha256': persona['source']['sha256']})
        # Full silhouette preserved; no center crop or generative changes.
        social = Image.new('RGBA', (1200, 630), persona['colors']['surface'])
        draw = ImageDraw.Draw(social)
        draw.rounded_rectangle((720, 35, 1160, 595), radius=100 if persona['id'] == 'wisteria' else 24, fill=persona['colors']['motif'])
        figure = image.resize((420, 560), Image.Resampling.LANCZOS)
        social.alpha_composite(figure, (750, 35))
        draw = ImageDraw.Draw(social)
        title_font = ImageFont.load_default(size=44 if len(persona['project']) < 18 else 36)
        draw.text((60, 120), 'IrisSakura / Projects', fill=persona['colors']['primary'], font=ImageFont.load_default(size=22))
        draw.text((60, 238), persona['project'], fill=persona['colors']['primary'], font=title_font)
        draw.text((60, 320), persona['tagline'].replace('·', '/'), fill=persona['colors']['primary'], font=ImageFont.load_default(size=24))
        draw.line((60, 392, 580, 392), fill=persona['colors']['accent'], width=5)
        (base / 'social').mkdir(exist_ok=True)
        social.convert('RGB').save(base / 'social/card.png', optimize=True)

css = ['/* Generated by scripts/build-personas-v2.py from config/personas-v2.json. */', ':root {']
for persona in config['personas']:
    for role, color in persona['colors'].items():
        css.append(f"  --persona-{persona['id']}-{role}: {color};")
css.append('}')
for persona in config['personas']:
    selectors = f'[data-persona="{persona["id"]}"], html[data-brand-mode="{persona["mode"]}"]'
    css.append(selectors + ' {')
    for role in persona['colors']:
        css.append(f"  --persona-{role}: var(--persona-{persona['id']}-{role});")
    css.append('}')
(ROOT / 'style/tokens/personas-v2.css').write_text('\n'.join(css) + '\n')
(ROOT / 'assets/personas/v2/manifest.json').write_text(json.dumps({'visualBaseline': config['visualBaseline'], 'derivation': 'PNG masters to proportionally resized AVIF/WebP; alpha retained; no generative changes or crops.', 'assets': records}, indent=2) + '\n')
print(f'Derived {len(records)} responsive images and six social cards.')
